// This file is part of AetherAprs
// SPDX-FileCopyrightText: 2026 Rui Oliveira <ruimail24@gmail.com>
// SPDX-License-Identifier: GPL-3.0-or-later

// <auto-generated />
using System;
using AetherAprs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AetherAprs.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918122925_RemovePortSsidAndSymbol")]
    partial class RemovePortSsidAndSymbol
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AetherAprs.Data.BeaconConfigRecord", b =>
                {
                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BeaconComment")
                        .HasMaxLength(43)
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseChangeThresholdDegrees")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("FastIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FastSpeedThresholdKmh")
                        .HasColumnType("REAL");

                    b.Property<int>("MinimumDistanceMeters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NormalIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlowIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SlowSpeedThresholdKmh")
                        .HasColumnType("REAL");

                    b.HasKey("Mode");

                    b.ToTable("BeaconConfigs", (string)null);
                });

            modelBuilder.Entity("AetherAprs.Data.BeaconingStateRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BeaconingState", (string)null);
                });

            modelBuilder.Entity("AetherAprs.Data.MessageRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutbound")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MessageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Peer")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PortId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(67)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Peer");

                    b.HasIndex("Timestamp");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("AetherAprs.Data.PortRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DynamicBeaconMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRx")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowOnMap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ports", (string)null);
                });

            modelBuilder.Entity("AetherAprs.Data.PortRecord", b =>
                {
                    b.OwnsOne("AetherAprs.Data.AprsIsSettingsRecord", "AprsIs", b1 =>
                        {
                            b1.Property<Guid>("PortRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Filter")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Passcode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Server")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<int>("ServerPort")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PortRecordId");

                            b1.ToTable("Ports");

                            b1.WithOwner()
                                .HasForeignKey("PortRecordId");
                        });

                    b.OwnsOne("AetherAprs.Data.KissSettingsRecord", "Kiss", b1 =>
                        {
                            b1.Property<Guid>("PortRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Transport")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("TEXT");

                            b1.HasKey("PortRecordId");

                            b1.ToTable("Ports");

                            b1.WithOwner()
                                .HasForeignKey("PortRecordId");

                            b1.OwnsOne("AetherAprs.Data.BluetoothClassicKissTransportRecord", "BluetoothClassic", b2 =>
                                {
                                    b2.Property<Guid>("KissSettingsRecordPortRecordId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("DeviceAddress")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("DeviceName")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("KissSettingsRecordPortRecordId");

                                    b2.ToTable("Ports");

                                    b2.WithOwner()
                                        .HasForeignKey("KissSettingsRecordPortRecordId");
                                });

                            b1.OwnsOne("AetherAprs.Data.BluetoothLeKissTransportRecord", "BluetoothLe", b2 =>
                                {
                                    b2.Property<Guid>("KissSettingsRecordPortRecordId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("DeviceAddress")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("DeviceName")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("RxCharacteristicUuid")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("ServiceUuid")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("TxCharacteristicUuid")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("KissSettingsRecordPortRecordId");

                                    b2.ToTable("Ports");

                                    b2.WithOwner()
                                        .HasForeignKey("KissSettingsRecordPortRecordId");
                                });

                            b1.OwnsOne("AetherAprs.Data.TcpKissTransportRecord", "Tcp", b2 =>
                                {
                                    b2.Property<Guid>("KissSettingsRecordPortRecordId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Host")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Port")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("KissSettingsRecordPortRecordId");

                                    b2.ToTable("Ports");

                                    b2.WithOwner()
                                        .HasForeignKey("KissSettingsRecordPortRecordId");
                                });

                            b1.Navigation("BluetoothClassic");

                            b1.Navigation("BluetoothLe");

                            b1.Navigation("Tcp");
                        });

                    b.Navigation("AprsIs");

                    b.Navigation("Kiss");
                });
#pragma warning restore 612, 618
        }
    }
}
